name: retroX

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-minutes: 9999

    steps:

    - name: Download Ngrok.

      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/megamandev/retroX/main/main.bat -OutFile main.bat
        Invoke-WebRequest https://raw.githubusercontent.com/megamandev/retroX/main/image.bat -OutFile image.bat
        Invoke-WebRequest https://raw.githubusercontent.com/megamandev/retroX/main/repeat.bat -OutFile repeat.bat
        Invoke-WebRequest https://raw.githubusercontent.com/megamandev/retroX/main/main.bat -OutFile push.bat
    - name: Extract Ngrok File.

      run: Expand-Archive ngrok.zip

    - name: Connect Ngrok.

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: retroX.

      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy image.bat D:\a\image.bat
    - name: Tunnel.

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region sa 3389"'

    - name: Connect cloud.

      run: cmd /c main.bat

    - name: Cloud latest.

      run: cmd /c repeat.bat
